package com.hr.service;

// GoF Design Pattern: Strategy — concrete PDF strategy.
// Justification: PDF is the required format for legal archival and external auditors.
// Encapsulating PDF-specific layout rules here means the format can be updated
// (e.g. switching from iText to Apache PDFBox) without touching ReportGenerator.

public class PdfFormatStrategy implements ReportFormatStrategy {

    @Override
    public String format(String data) {
        return "[PDF REPORT]\n"
                + "========================================\n"
                + data + "\n"
                + "========================================\n"
                + "Generated by HR System | Format: PDF";
    }

    @Override
    public String getFormatName() { return "PDF"; }
}
